sudi: required
language: bash

env:
  global:
  - IMAGE_NAME=gableroux/unity3d:2018.2.6f1
  - FOO=foo

services:
- docker

jobs:
  include:
  - stage: test
    script: ./execute_docker.sh
  - stage: test
    env: IMAGE_NAME=ubuntu:16.04
    script: ./execute_docker.sh
  - stage: test
    env: FOO=bar
    script: ./execute_docker.sh